name: coverage
on:
  pull_request:
    branches:
      - dev
jobs:
  check-coverage:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repository
      - uses: actions/checkout@v2

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            threshold: 80

      - name: Coverage ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "coverage",
            "state": "success",
            "description": "Coverage passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      
      - name: Coverage 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "coverage",
            "state": "failure",
            "description": "Coverage failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'