name: coverage
on:
  pull_request:
    branches:
      - dev
jobs:
  check-coverage:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repository
      - uses: actions/checkout@v2

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            threshold: 80