name: Test Action
on:
  push:
  pull_request:
    branches:
      - dev
jobs:
  run-test-command:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test