name: tests
on:
  push:
  pull_request:
    branches:
      - dev
jobs:
  make-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repository
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Test Passed Slack Notif ✅
        if: ${{ success() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: continuous-integration
          status: SUCCESS-TEST
          color: good
      
      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

  check-coverage:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repository
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      - run: npm install

      - run: npm run coverage
          
      - run: |
          python3 coverageVerificator.py coverage/coverage-summary.json ${{ secrets.THRESHOLD }}

  # notify-slack:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send Notification to Slack
  #       uses: voxmedia/github-action-slack-notify-build@v1
  #       with:
  #         channel: continuous-integration
  #         status: SUCCESS
  #         color: good
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}